Repository rairprotocol/rair-dapp, pull requests merged in 2024-10, with the labels that each got.

#233 232 - wrong error message on collection view mint
  rair-front/src/components/MockUpPage/NftList/NftData/SerialNumberBuySell.tsx
  rair-front/src/components/Navigation/Menu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/UserProfileSettings/PopUpSetting.tsx
  rair-front/src/components/common/PurchaseToken.tsx
Labels: frontend

#235 234 - Set default values on Server Settings if color is not set
  rair-front/src/components/ServerSettings/colorSettings.tsx
  rair-front/src/redux/colorSlice.ts
  rair-node/bin/api/transactions/transactions.Controller.js
  rair-node/bin/models/serverSettings.js
Labels: frontend

#239 238 - Missing pagination
  rair-front/src/components/MockUpPage/PaginationBox/PaginationBox.tsx
  rair-front/src/components/MockUpPage/PaginationBox/PaginationBoxStyled.tsx
Labels: frontend

#240 196 - missing token data
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/SelectNumber.tsx
Labels: frontend

#229 220 notifications not displayed on mobile
  rair-front/src/App.tsx
  rair-front/src/components/DemoMediaUpload/MediaItemChange/MediaItemChange.tsx
  rair-front/src/components/DemoMediaUpload/PopUpChangeVideo/PopUpChangeVideo.tsx
  rair-front/src/components/DemoMediaUpload/UploadedListBox/UploadedListBox.tsx
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/MockUpPage/FilteringBlock/FilteringBlockItems/FilteringBlockItems.tsx
  rair-front/src/components/MockUpPage/PaginationBox/PaginationBox.tsx
  rair-front/src/components/MockUpPage/PaginationBox/PaginationBoxStyled.tsx
  rair-front/src/components/Navigation/Menu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileChoiseNav.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileListMenu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/Navigation/NavigationItems/NavigationItems.tsx
  rair-front/src/components/UserProfileSettings/PopUpNotification/NotificationBox/NotificationBox.tsx
  rair-front/src/components/UserProfileSettings/PopUpNotification/PopUpNotification.tsx
  rair-front/src/components/nft/PersonalProfile/PersonalProfileMyNftTab/ResaleModal/ResaleModal.tsx
  rair-front/src/images/index.tsx
  rair-front/src/redux/notificationsSlice.ts
  rair-front/src/redux/store.ts
  rair-front/src/styled-components/SocialLinkIcons/SocialLinkIcons.tsx
Labels: bug, frontend

#246 Fix refresh on filter
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/TitleCollection/FilterMetadataTokens/MetadataAttrPropertyItems/MetadataAttributesPropertyItem.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/TitleCollection/FilterMetadataTokens/MetadataItem.tsx
  rair-node/bin/schemas/v2AuthSchemas.js
Labels: frontend

#241 Fix style issue for serial number picker when there are more than a thousand tokens
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/SelectNumber.tsx
Labels: bug, frontend

#249 247 - slow loading of tokens
  rair-front/src/App.tsx
  rair-front/src/redux/tokenSlice.ts
Labels: frontend

#250 243 clear all button should be disabled when no notifications exists
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/UserProfileSettings/PopUpNotification/PopUpNotification.tsx
Labels: bug, frontend

#251 Add sorting of items/videos to the Main Page
  rair-front/src/components/MockUpPage/NftList/NftList.tsx
  rair-front/src/components/MockUpPage/SearchPanel.tsx
  rair-front/src/components/video/video.types.ts
  rair-front/src/components/video/videoList.tsx
Labels: bug, frontend

#258 Change category on Video Manger
  rair-front/src/components/DemoMediaUpload/MediaItemChange/MediaItemChange.tsx
  rair-front/src/components/DemoMediaUpload/PopUpChangeVideo/PopUpChangeVideo.tsx
  rair-front/src/components/DemoMediaUpload/UploadedListBox/UploadedListBox.tsx
  rair-front/src/components/videoManager/VideoManager.tsx
  rair-node/bin/api/files/files.Service.js
  rair-node/bin/api/users/users.Controller.js
  rair-node/bin/api/users/users.Service.js
Labels: frontend, backend

#259 Ignore demos if blockchain filter is on
  rair-front/src/components/video/videoItem.tsx
  rair-node/bin/api/files/files.Service.js
Labels: frontend, backend

#261 257 provide indication to user in case loading of nfts is taking time in collection view
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/redux/tokenSlice.ts
Labels: bug, frontend

#260 Use AND logic in metadata filters
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-node/bin/api/nft/nft.Service.js
Labels: backend

#262 256 - Rate limiting
  rair-node/bin/index.js
  rair-node/package.json
Labels: backend

#268 267 - Message if not logged in
  rair-front/src/components/MockUpPage/NftList/LikeButton/LikeButton.tsx
  rair-front/src/components/common/PurchaseToken.tsx
Labels: frontend
