Repository rairprotocol/rair-dapp, pull requests merged in 2024-05, with the labels that each got.

#19 #17 - Update OFAC script
  rair-node/bin/api/auth/auth.Service.js
  rair-node/ofac-sanctioned-digital-currency-addresses/generate-address-list.py
Labels: bug, backend

#22 #8 - Tool for ERC20 transfers
  rair-front/src/components/adminViews/BatchERC20Transfer.tsx
  rair-front/src/components/adminViews/ImportExternalContracts.tsx
  rair-front/src/hooks/useWeb3Tx.ts
Labels: enhancement, frontend

#23 Fix: Homepage class error issue in frontend preventing metadata image display
  rair-front/src/components/MockUpPage/ImageLazy/ImageLazy.tsx
Labels: frontend

#26 Add hover effect for admin links and remove "Add Media" from Server settings page
  rair-front/src/App.tsx
  rair-front/src/components/Header/AdminPanel/AdminPanel.tsx
  rair-front/src/components/adminViews/ImportAndTransfer.tsx
  rair-front/src/components/adminViews/ImportExternalContracts.tsx
  rair-front/src/components/adminViews/transferTokens.tsx
  rair-front/src/components/video/videoUpload/videoUpload.tsx
Labels: frontend

#33 Fix image issue
  rair-front/src/components/MockUpPage/ImageLazy/ImageLazy.tsx
Labels: bug, frontend

#42 update superadmin script
  rair-infra/commands/update-local-admin/mongo_commands.js
  rair-infra/commands/update-local-admin/update_local_admin.sh
Labels: devops

#32 Add Pop-up for User balance | Desktop and Mobile
  rair-front/src/components/Navigation/Menu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/UserProfileSettings/PopUpSetting.tsx
  rair-front/src/images/index.tsx
Labels: frontend

#46 Update contract URL in Footer
  rair-front/src/components/Footer/Footer.tsx
Labels: frontend
