Repository rairprotocol/rair-dapp, pull requests merged in 2024-06, with the labels that each got.

#60 Throw error if GCP storage cannot initialize
  rair-front/src/components/DemoMediaUpload/MediaListBox/MediaListBox.tsx
  rair-node/bin/api/upload/upload.Service.js
  rair-stream/.dockerignore
  rair-stream/bin/api/upload/upload.service.js
  rair-stream/bin/index.js
  rair-stream/bin/integrations/gcp/index.js
Labels: backend

#62 Reorder checks
  rair-node/bin/integrations/ethers/importContractData.js
Labels: backend

#66 Fix
  rair-node/bin/api/nft/nft.Service.js
  rair-node/bin/models/mintedToken.js
Labels: backend

#61 Multiple alchemy connections
  rair-front/package.json
  rair-front/src/App.tsx
  rair-front/src/components/DemoMediaUpload/MediaItemChange/MediaItemChange.tsx
  rair-front/src/components/DemoMediaUpload/MediaListBox/MediaListBox.tsx
  rair-front/src/components/DemoMediaUpload/UploadedListBox/AnalyticsPopUp/AnalyticsPopUp.tsx
  rair-front/src/components/DemoMediaUpload/UploadedListBox/UploadedListBox.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SellButton.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/ListOfTokens/ListOfTokens.tsx
  rair-front/src/components/adminViews/BatchERC20Transfer.tsx
  rair-front/src/components/common/PurchaseToken.tsx
  rair-front/src/components/creatorStudio/diamondCreatorSteps/diamondOfferRow.tsx
  rair-front/src/hooks/useConnectUser.tsx
  rair-front/src/hooks/useWeb3Tx.ts
  rair-front/src/utils/blockchainData.ts
  rair-front/src/utils/utils.types.ts
  rair-node/bin/api/settings/settings.Controller.js
  rair-node/bin/api/settings/settings.Service.js
  rair-node/bin/api/tokens/tokens.Controller.js
  rair-node/bin/api/tokens/tokens.Service.js
  rair-sync/bin/utils/eventCatcherUtils/createResaleOffer.js
  rair-sync/bin/utils/eventCatcherUtils/sellResaleOffer.js
  rair-sync/bin/utils/reusableTransactionHandler.js
Labels: frontend

#70 Read and Unread Filters
  rair-node/bin/api/notifications/notifications.Controller.js
  rair-node/bin/api/notifications/notifications.Service.js
  rair-node/bin/schemas/index.js
  rair-node/bin/schemas/notifications.js
Labels: backend

#73 Remove Sold out text from preview token and add to hover effect
  rair-front/src/components/MockUpPage/GeneralCollectionStyles.css
  rair-front/src/components/MockUpPage/NftList/NftItemForCollectionView.tsx
Labels: frontend

#71 Style fix
  rair-front/src/components/DemoMediaUpload/MediaListBox/MediaListBox.tsx
Labels: backend

#76 Close Swal after successful upload
  rair-front/src/components/DemoMediaUpload/MediaListBox/MediaListBox.tsx
Labels: bug, frontend

#78 Remove user data query call
  rair-front/src/components/MockUpPage/NftList/NftItem.tsx
  rair-front/src/components/MockUpPage/NftList/NftList.tsx
  rair-front/src/components/MockUpPage/NftList/nftList.types.ts
  rair-front/src/components/ResalePage/ListOffers.tsx
  rair-front/src/components/UserProfilePage/UserProfilePage.tsx
  rair-front/src/ducks/nftData/action.ts
  rair-front/src/ducks/nftData/saga.ts
  rair-front/src/images/index.tsx
  rair-node/bin/api/contracts/contracts.Service.js
  rair-node/bin/integrations/ethers/importContractData.js
Labels: backend
