Repository rairprotocol/rair-dapp, pull requests merged in 2024-08, with the labels that each got.

#140 133 - Automatic super admin on first signup
  rair-front/src/App.tsx
  rair-front/src/components/Header/AdminPanel/AdminPanel.tsx
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/Navigation/Menu.tsx
  rair-node/bin/api/users/users.Controller.js
  rair-node/bin/api/users/users.Service.js
Labels: backend

#139 136 - backend demo dummy fields for database
  rair-front/src/components/adminViews/ServerSettings.tsx
  rair-front/src/components/adminViews/useServerSettings.tsx
  rair-front/src/components/common/commonTypes/InputSelectTypes.types.ts
  rair-node/bin/api/settings/settings.Service.js
  rair-node/bin/models/serverSettings.js
  rair-node/bin/schemas/databaseSchemas.js
Labels: frontend, backend

#161 152 - Prevent duplicate notifications
  rair-sync/bin/utils/eventCatcherUtils/insertContract.js
  rair-sync/bin/utils/logUtils.js
  rair-sync/bin/utils/reusableTransactionHandler.js
Labels: backend

#160 156 - Transaction catcher with Alchemy/RPC switch
  rair-sync/bin/integrations/ethers/transactionCatcher.js
  rair-sync/bin/tasks/sync.js
  rair-sync/bin/utils/logUtils.js
Labels: backend

#162 79 - Profile page error
  rair-front/src/components/MockUpPage/NftList/NftItemForCollectionView.tsx
  rair-front/src/components/UserProfilePage/UserProfilePage.tsx
Labels: frontend

#149 148 option to mint multiple nfts in case of minting sponsored to be disabled
  SECURITY.md
  rair-front/src/components/MockUpPage/NftList/NftData/CollectionInfo/CollectionInfo.tsx
Labels: frontend

#166 163 - Remove raw IPFS client
  rair-node/bin/api/files/files.Service.js
  rair-node/bin/integrations/ipfsService/index.js
  rair-node/bin/integrations/ipfsService/ipfs.js
  rair-node/bin/utils/logger.js
  rair-node/package.json
  rair-stream/.eslintrc.json
  rair-stream/.prettierignore
  rair-stream/.prettierrc
  rair-stream/Dockerfile
  rair-stream/Dockerfile.prod
  rair-stream/bin/integrations/ipfsService/index.js
  rair-stream/bin/integrations/ipfsService/ipfs.js
  rair-stream/bin/integrations/ipfsService/pinata.js
  rair-stream/eslint.config.mjs
  rair-stream/package-lock.json
  rair-stream/package.json
Labels: backend

#165 58 - Remove unused User Page
  rair-front/src/App.css
  rair-front/src/App.tsx
  rair-front/src/components/UserProfile/UserProfile.css
  rair-front/src/components/UserProfile/UserProfile.tsx
  rair-front/src/components/nft/MyItems.css
  rair-front/src/styles/userProfile.css
  rair-node/README.md
  rair-node/bin/api/nft/nft.Controller.js
  rair-node/bin/api/nft/nft.Service.js
  rair-node/readme/current/nft/nft_get_current.md
Labels: frontend, backend

#167 164 - Update token count logic
  rair-sync/bin/utils/eventCatcherUtils/insertTokenDiamond.js
  rair-sync/bin/utils/eventCatcherUtils/transferredToken.js
Labels: backend

#172 171 - Validation on login
  rair-node/bin/integrations/ethers/web3Signature.js
Labels: backend
