Repository rairprotocol/rair-dapp, pull requests merged in 2024-07, with the labels that each got.

#85 Minor Text changes
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/MockUpPage/SearchPanel.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileListMenu.tsx
Labels: frontend

#83 Category config and login message
  rair-front/src/components/adminViews/ServerSettings.tsx
  rair-front/src/components/adminViews/useServerSettings.tsx
  rair-node/bin/api/auth/auth.Service.js
  rair-node/bin/api/categories/categories.Controller.js
  rair-node/bin/api/categories/categories.Service.js
  rair-node/bin/integrations/ethers/importContractData.js
  rair-node/bin/models/serverSettings.js
  rair-node/bin/routes/index.js
  rair-node/bin/schemas/databaseSchemas.js
  rair-node/bin/seeds/index.js
Labels: frontend, backend

#91 90 - Notifications update backend
  rair-node/bin/api/notifications/notifications.Controller.js
  rair-node/bin/api/notifications/notifications.Service.js
  rair-node/bin/models/notification.js
  rair-node/bin/schemas/commonApiSchemas.js
  rair-node/bin/schemas/index.js
  rair-node/readme/current/notifications/mark_read.md
Labels: backend

#95 Update Notifications GET
  rair-node/bin/api/nft/nft.Service.js
  rair-node/bin/api/notifications/notifications.Service.js
  rair-node/readme/current/notifications/get_list.md
Labels: backend

#97 92 serial number picker backend endpoint
  rair-node/README.md
  rair-node/bin/api/nft/nft.Controller.js
  rair-node/bin/api/nft/nft.Service.js
  rair-node/bin/api/tokens/tokens.Controller.js
  rair-node/bin/api/tokens/tokens.Service.js
  rair-node/bin/schemas/v2TokenSchemas.js
  rair-node/readme/current/nft/nft_manual_attributes.md
  rair-node/readme/current/nft/nft_manual_files.md
  rair-node/readme/current/nft/nft_manual_files_token.md
  rair-node/readme/current/nft/nft_manual_locks.md
  rair-node/readme/current/nft/nft_manual_numbers.md
  rair-node/readme/current/nft/nft_manual_offers.md
  rair-node/readme/current/nft/nft_manual_product.md
  rair-node/readme/current/tokens/tokens_numbers.md
Labels: backend

#99 Update
  rair-node/README.md
  rair-node/bin/api/notifications/notifications.Controller.js
  rair-node/bin/api/notifications/notifications.Service.js
  rair-node/readme/current/notifications/delete.md
  rair-node/readme/current/notifications/mark_read.md
Labels: backend

#108 Optional array of IDs to mark as read/delete all
  rair-node/bin/api/notifications/notifications.Controller.js
  rair-node/bin/api/notifications/notifications.Service.js
Labels: backend

#113 Clear all notifications pagination
  rair-front/src/App.tsx
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/MockUpPage/PaginationBox/PaginationBox.tsx
  rair-front/src/components/MockUpPage/mockupPage.types.ts
  rair-front/src/components/Navigation/Menu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileChoiseNav.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/UserProfileSettings/NotificationPage/NotificationPage.css
  rair-front/src/components/UserProfileSettings/NotificationPage/NotificationPage.tsx
  rair-front/src/components/UserProfileSettings/PopUpNotification/NotificationBox/NotificationBox.css
  rair-front/src/components/UserProfileSettings/PopUpNotification/PopUpNotification.tsx
  rair-front/src/components/UserProfileSettings/UserProfileSettings.css
Labels: frontend

#111 94 update theming elements header text color to primary button color for icons
  README.md
  rair-front/src/components/Footer/Footer.tsx
  rair-front/src/components/Footer/FooterItems/FooterItems.tsx
  rair-front/src/components/Header/AdminPanel/AdminPanel.tsx
  rair-front/src/components/Header/HeaderItems/HeaderItems.tsx
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/MockUpPage/FilteringBlock/FilteringBlock.tsx
  rair-front/src/components/MockUpPage/FilteringBlock/FilteringBlockItems/FilteringBlockItems.tsx
  rair-front/src/components/MockUpPage/FilteringBlock/filteringBlock.types.ts
  rair-front/src/components/MockUpPage/NftList/Breadcrumbs/Breadcrumbs.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SellInputButton.tsx
  rair-front/src/components/MockUpPage/SearchPanel.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/CurrentTokens/CurrentTokens.tsx
  rair-front/src/components/Navigation/Menu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileListMenu.tsx
  rair-front/src/components/Navigation/NavigationItems/NavigationItems.tsx
  rair-front/src/components/UserProfilePage/UserProfilePage.tsx
  rair-front/src/components/UserProfileSettings/PopUpSetting.tsx
  rair-front/src/components/UserProfileSettings/SettingsIcons/SettingsIcons.tsx
  rair-front/src/components/adminViews/ServerSettings.tsx
  rair-front/src/components/adminViews/useServerSettings.tsx
  rair-front/src/components/common/LoadingComponent.tsx
  rair-front/src/components/creatorStudio/Contracts.tsx
  rair-front/src/components/creatorStudio/ListCollections.tsx
  rair-front/src/ducks/colors/colorStore.types.ts
  rair-front/src/ducks/colors/reducer.ts
Labels: bug, frontend

#121 114 rair node stopped with error error invalid signature v value
  rair-node/Dockerfile
  rair-node/Dockerfile.prod
  rair-node/bin/integrations/ethers/web3Signature.js
Labels: backend

#122 118 homepage displaying 0x address instead of user profile name when name exists
  rair-front/src/axios.responseTypes.ts
  rair-front/src/ducks/nftData/saga.ts
Labels: bug, frontend

#124 Add v1 of contributing md to repo
  Contributing to RAIRprotocol.md
Labels: documentation

#131 Set default loading favicon
  rair-front/index.html
  rair-front/public/favicons/loading-favicon.svg
  rair-front/src/ducks/seo/reducers.ts
  rair-front/src/images/index.tsx
  rair-front/src/images/loading-favicon.svg
Labels: bug, frontend

#89 Fix issue serial number picker
  rair-front/src/axios.responseTypes.ts
  rair-front/src/components/MockUpPage/NftList/NftData/NftDataCommonLink.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/NftDataPageMain.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SerialNumberBuySell.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/CurrentTokens/CurrentTokens.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/ListOfTokens/ListOfTokens.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/SelectNumber.tsx
  rair-front/src/components/MockUpPage/SelectBox/selectBox.types.ts
Labels: enhancement, frontend

#134 add func for Clear all
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileChoiseNav.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/UserProfileSettings/PopUpNotification/NotificationBox/NotificationBox.tsx
  rair-front/src/components/UserProfileSettings/PopUpNotification/PopUpNotification.tsx
  rair-front/src/components/UserProfileSettings/UserProfileSettings.css
Labels: frontend

#138 Sort order of notifications
  rair-front/src/App.tsx
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
Labels: bug, frontend
