Repository rairprotocol/rair-dapp, pull requests merged in 2024-09, with the labels that each got.

#177 Update .env.sample
  rair-front/.env.sample
Labels: documentation

#182 New env sample structure
  rair-front/env-templates/opencarbon.sample
Labels: documentation

#181 180 - Clear token data when collection loads
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/NftDataCommonLink.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/NftDataExternalLink.tsx
  rair-front/src/components/MockUpPage/mockupPage.types.ts
  rair-front/src/redux/tokenSlice.ts
  rair-node/bin/api/nft/nft.Service.js
  rair-node/bin/api/products/product.Controller.js
  rair-node/bin/api/products/product.Service.js
Labels: frontend

#187 Populate Base data
  rair-node/bin/index.js
  rair-node/bin/seeds/index.js
Labels: backend

#188 186 fix video filtering
  rair-front/src/components/GlobalModal/FilterModal/FilterModal.tsx
  rair-front/src/components/MockUpPage/SearchPanel.tsx
  rair-front/src/redux/videoSlice.ts
  rair-node/bin/api/files/files.Service.js
Labels: frontend, backend

#193 Correct vide query params on User Profile Page
  rair-front/src/components/nft/PersonalProfile/PersonalProfileMyVideoTab/PersonalProfileMyVideoTab.tsx
  rair-front/src/redux/videoSlice.ts
Labels: frontend

#192 Infinite loop on Metadata Filter
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/TitleCollection/FilterMetadataTokens/ClearMetadataBox/ClearMetadataItem.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/TitleCollection/FilterMetadataTokens/MetadataAttrPropertyItems/MetadataAttributesPropertyItem.tsx
Labels: frontend

#198 Fix percentages
  rair-front/src/components/creatorStudio/creatorSteps/ResaleMarketplace.tsx
Labels: frontend

#197 194 - BigInt error in advanced offers page
  rair-front/src/components/creatorStudio/diamondCreatorSteps/MarketplaceOfferConfig.tsx
Labels: frontend

#202 199 - Clear notification data when logged out
  rair-front/src/App.tsx
  rair-front/src/components/Header/MainHeader.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SerialNumberBuySell.tsx
  rair-front/src/components/Navigation/Menu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileChoiseNav.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/UserProfileSettings/PopUpNotification/PopUpNotification.tsx
Labels: frontend

#203 200 - Api call result handling
  rair-front/src/components/creatorStudio/creatorSteps/singleMetadataEditor.tsx
  rair-front/src/components/marketplace/marketplace.types.ts
Labels: frontend

#189 Add Minato data
  rair-front/src/components/ServerSettings/blockchainSettings.tsx
  rair-front/src/hooks/useContracts.tsx
  rair-front/src/hooks/useServerSettings.tsx
  rair-front/src/hooks/useWeb3Tx.ts
  rair-front/src/images/index.tsx
  rair-front/src/images/sonium_logo.svg
  rair-front/src/redux/web3Slice.ts
  rair-front/src/utils/blockchainData.ts
  rair-front/src/utils/utils.types.ts
Labels: frontend

#205 142 - random token mint
  rair-front/src/components/common/PurchaseToken.tsx
  rair-front/src/components/common/commonTypes/PurchaseTokenTypes.types.ts
  rair-node/bin/api/offers/offers.Controller.js
  rair-node/bin/api/offers/offers.Service.js
Labels: frontend, backend

#214 Fix created page profile
  rair-front/src/axios.responseTypes.ts
  rair-front/src/components/MockUpPage/NftList/nftList.types.ts
  rair-front/src/components/UserProfilePage/UserProfileCreated/UserProfileCreated.tsx
  rair-front/src/components/UserProfilePage/UserProfilePage.tsx
  rair-front/src/components/creatorStudio/creatorSteps/batchMetadata.tsx
  rair-front/src/components/creatorStudio/creatorStudio.types.ts
Labels: frontend

#217 Show user's address
  rair-front/src/components/MockUpPage/MainBanner/MainBanner.tsx
  rair-node/bin/api/settings/settings.Service.js
Labels: frontend, backend

#209 208 - Reload token data
  rair-front/src/components/MockUpPage/NftList/NftData/NftDataCommonLink.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SerialNumberBuySell.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/SelectNumber.tsx
Labels: frontend

#210 207 - Social mint query and refresh
  rair-front/src/axios.responseTypes.ts
  rair-front/src/components/MockUpPage/NftList/NftData/CollectionInfo/CollectionInfo.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SerialNumberBuySell.tsx
  rair-front/src/components/common/PurchaseToken.tsx
  rair-front/src/components/creatorStudio/creatorStudio.types.ts
  rair-front/src/hooks/useContracts.tsx
  rair-front/src/hooks/useWeb3Tx.ts
  rair-front/yarn.lock
Labels: frontend

#222 221 - authentication error
  rair-front/src/components/Footer/FooterItems/FooterItems.tsx
  rair-front/src/components/Navigation/Menu.tsx
  rair-front/src/components/Navigation/MenuComponents/MobileNavigationList.tsx
  rair-front/src/components/Navigation/NavigationItems/NavigationItems.tsx
  rair-front/src/components/common/PurchaseToken.tsx
  rair-front/src/hooks/useWeb3Tx.ts
Labels: frontend

#204 201 - resale offer errors
  rair-front/src/App.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/NftDataCommonLink.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SellButton.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SerialNumberBuySell.tsx
  rair-front/src/components/MockUpPage/mockupPage.types.ts
  rair-front/src/components/UserProfilePage/UserProfilePage.tsx
  rair-front/src/components/nft/PersonalProfile/PersonalProfileMyNftTab/PersonalProfileMyNftTab.tsx
  rair-front/src/components/nft/PersonalProfile/PersonalProfileMyNftTab/ResaleModal/ResaleModal.tsx
  rair-front/src/components/nft/myItems.tsx
  rair-front/src/contracts/diamondMarketplaceABI.json
  rair-front/src/hooks/useWeb3Tx.ts
  rair-front/src/redux/tokenSlice.ts
  rair-front/src/redux/web3Slice.ts
  rair-front/src/types/commonTypes.ts
  rair-node/bin/api/credits/credits.Service.js
  rair-node/bin/api/nft/nft.Service.js
  rair-node/bin/api/products/product.Service.js
  rair-node/bin/api/resales/resales.Service.js
  rair-sync/bin/integrations/ethers/contracts/diamondMarketplaceABI.json
  rair-sync/bin/utils/eventCatcherMapping.js
  rair-sync/bin/utils/eventCatcherUtils/deleteResaleOffer.js
  rair-sync/bin/utils/eventCatcherUtils/index.js
  rair-sync/bin/utils/eventCatcherUtils/updateResaleOffer.js
Labels: frontend

#225 223 switch theme icon button works in mobile
  rair-front/src/components/Navigation/MenuComponents/MobileChoiseNav.tsx
  rair-front/src/images/index.tsx
Labels: bug

#227 Load resale data from collection
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/components/MockUpPage/NftList/NftItemForCollectionView.tsx
  rair-front/src/redux/tokenSlice.ts
Labels: frontend

#228 Use internal numbering
  rair-front/src/components/MockUpPage/NftList/NftData/NftCollectionPage.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/NftDataCommonLink.tsx
  rair-front/src/components/MockUpPage/NftList/NftData/SellButton.tsx
  rair-front/src/components/MockUpPage/SelectBox/SelectNumber/SelectNumber.tsx
  rair-front/src/components/creatorStudio/creatorSteps/ListOffers.tsx
  rair-front/src/components/creatorStudio/diamondCreatorSteps/ListOffersDiamond.tsx
  rair-front/src/components/nft/PersonalProfile/PersonalProfileMyNftTab/ResaleModal/ResaleModal.tsx
  rair-front/src/redux/tokenSlice.ts
  rair-node/bin/utils/entityFactory.js
Labels: frontend

#231 Remove default seo values
  rair-front/src/hooks/useServerSettings.tsx
  rair-front/src/redux/seoSlice.ts
Labels: frontend
